export const UiFrameworks = [
  "NextUI",
  "RadixUI",
  "ShadcnUI",
  "Mantine",
  "MaterialUI",
  "ChakraUI",
  "AntDesign",
];

export const frameworkDetails: {
  [framework: string]: {
    logo: string;
    configurationMethods: string;
    specialInstallationRequirements: string;
    license: string;
    pricing: string;
    RTLsupport: string;
    github: string;
    website: string;
    docs: string;
  };
} = {
  AntDesign: {
    RTLsupport: "Yes",
    configurationMethods: "Ant Design Theme and props for functionality",
    docs: "https://ant.design/components/overview/",
    github: "https://github.com/ant-design/ant-design",
    license: "MIT",
    logo: "/logos/antdesign.svg",
    pricing: "Free",
    specialInstallationRequirements:
      "Yes, in some cases, `ConfigProvider` for global configuration",
    website: "https://ant.design",
  },
  ChakraUI: {
    RTLsupport: "Yes",
    configurationMethods:
      "Theme provider for customization, props for functionality",
    docs: "https://chakra-ui.com/docs",
    github: "https://github.com/chakra-ui/chakra-ui",
    license: "MIT",
    logo: "/logos/chakraui.svg",
    pricing: "Free",
    specialInstallationRequirements:
      "Yes, `ChakraProvider` at the root of your application",
    website: "https://chakra-ui.com",
  },
  Mantine: {
    RTLsupport: "Yes",
    configurationMethods:
      "Theme provider for customization, props for functionality",
    docs: "https://mantine.dev/getting-started",
    github: "https://github.com/mantinedev/mantine",
    license: "MIT",
    logo: "/logos/mantine.svg",
    pricing: "Free",
    specialInstallationRequirements:
      "Yes, The application must be wrapped with MantineProvider",
    website: "https://mantine.dev",
  },
  MaterialUI: {
    RTLsupport: "Yes",
    configurationMethods:
      "Theme provider for customization, props for functionality",
    docs: "https://material-ui.com/docs",
    github: "https://github.com/mui-org/material-ui",
    license: "MIT",
    logo: "/logos/mui.svg",
    pricing:
      "Free, with premium templates and components available for purchase",
    specialInstallationRequirements:
      "Yes, `ThemeProvider` for applying global themes",
    website: "https://material-ui.com",
  },
  NextUI: {
    RTLsupport: "Limited",
    configurationMethods: "Tailwind CSS for styling, props for functionality",
    docs: "https://nextui.org/docs",
    github: "https://github.com/nextui-org/nextui",
    license: "MIT",
    logo: "/logos/nextui.png",
    pricing: "Free",
    specialInstallationRequirements:
      "No specific context provider needed for basic installation",
    website: "https://nextui.org",
  },
  RadixUI: {
    RTLsupport: "Yes",
    configurationMethods: "Props for functionality, styling via CSS",
    docs: "https://radix-ui.com/docs",
    github: "https://github.com/radix-ui/primitives",
    license: "MIT",
    logo: "/logos/radixui.svg",
    pricing: "Free",
    specialInstallationRequirements:
      "No, but encourages the use of their primitives for consistency",
    website: "https://radix-ui.com",
  },
  ShadcnUI: {
    RTLsupport: "Unknown",
    configurationMethods:
      "Tailwind CSS and Radix UI for styling, props for functionality",
    docs: "https://ui.shadcn.com/docs",
    github: "https://github.com/shadcn-ui/ui",
    license: "MIT",
    logo: "/logos/shadcnui.svg",
    pricing: "Free",
    specialInstallationRequirements:
      "No specific context provider, but installation via CLI for component selection",
    website: "https://ui.shadcn.com",
  },
};

export const supportedComponents: {
  [framework: string]: { [component: string]: number };
} = {
  AntDesign: {
    Affix: 1,
    Alert: 1,
    Anchor: 1,
    App: 1,
    AutoComplete: 1,
    Avatar: 1,
    Badge: 1,
    Breadcrumb: 1,
    Button: 1,
    Calendar: 1,
    Card: 1,
    Carousel: 1,
    Cascader: 1,
    Checkbox: 1,
    Collapse: 1,
    ColorPicker: 1,
    ConfigProvider: 1,
    DatePicker: 1,
    Descriptions: 1,
    Divider: 1,
    Drawer: 1,
    Dropdown: 1,
    Empty: 1,
    Flex: 1,
    FloatButton: 1,
    Form: 1,
    Grid: 1,
    Icon: 1,
    Image: 1,
    Input: 1,
    InputNumber: 1,
    Layout: 1,
    List: 1,
    Mentions: 1,
    Menu: 1,
    Message: 1,
    Modal: 1,
    Notification: 1,
    Pagination: 1,
    Popconfirm: 1,
    Popover: 1,
    Progress: 1,
    QRCode: 1,
    Radio: 1,
    Rate: 1,
    Result: 1,
    Segmented: 1,
    Select: 1,
    Skeleton: 1,
    Slider: 1,
    Space: 1,
    Spin: 1,
    Statistic: 1,
    Steps: 1,
    Switch: 1,
    Table: 1,
    Tabs: 1,
    Tag: 1,
    TimePicker: 1,
    Timeline: 1,
    Tooltip: 1,
    Tour: 1,
    Transfer: 1,
    Tree: 1,
    TreeSelect: 1,
    Typography: 1,
    Upload: 1,
    Util: 1,
    Watermark: 1,
  },
  ChakraUI: {
    Accordion: 1,
    Alert: 1,
    AlertDialog: 1,
    AspectRatio: 1,
    Avatar: 1,
    Badge: 1,
    Box: 1,
    Breadcrumb: 1,
    Button: 1,
    Card: 1,
    Center: 1,
    Checkbox: 1,
    CircularProgress: 1,
    CloseButton: 1,
    Code: 1,
    Container: 1,
    Divider: 1,
    Drawer: 1,
    Editable: 1,
    Flex: 1,
    FormControl: 1,
    Grid: 1,
    Heading: 1,
    Highlight: 1,
    Icon: 1,
    IconButton: 1,
    Image: 1,
    Input: 1,
    Kbd: 1,
    Link: 1,
    LinkOverlay: 1,
    List: 1,
    Menu: 1,
    Modal: 1,
    NumberInput: 1,
    PinInput: 1,
    Popover: 1,
    Portal: 1,
    Progress: 1,
    Radio: 1,
    RangeSlider: 1,
    Select: 1,
    ShowHide: 1,
    SimpleGrid: 1,
    Skeleton: 1,
    SkipNav: 1,
    Slider: 1,
    Spinner: 1,
    Stack: 1,
    Stat: 1,
    Stepper: 1,
    Switch: 1,
    Table: 1,
    Tabs: 1,
    Tag: 1,
    Text: 1,
    Textarea: 1,
    Toast: 1,
    Tooltip: 1,
    Transitions: 1,
    VisuallyHidden: 1,
    Wrap: 1,
  },
  Mantine: {
    Accordion: 1,
    Alert: 1,
    AspectRatio: 1,
    Autocomplete: 1,
    Avatar: 1,
    Badge: 1,
    Breadcrumbs: 1,
    Button: 1,
    Card: 1,
    Carousel: 1,
    Checkbox: 1,
    Chip: 1,
    CircularProgress: 1,
    Code: 1,
    Collapse: 1,
    Divider: 1,
    Drawer: 1,
    IconButton: 1,
    Image: 1,
    Input: 1,
    Inset: 1,
    Kbd: 1,
    Link: 1,
    List: 1,
    Mentions: 1,
    Modal: 1,
    Notification: 1,
    Pagination: 1,
    Popover: 1,
    Progress: 1,
    Radio: 1,
    RadioGroup: 1,
    Rate: 1,
    ScrollArea: 1,
    SegmentedControl: 1,
    Select: 1,
    Separator: 1,
    Skeleton: 1,
    Slider: 1,
    Spacer: 1,
    Spin: 1,
    Spinner: 1,
    Switch: 1,
    Table: 1,
    Tabs: 1,
    Tag: 1,
    TextField: 1,
    Textarea: 1,
    TimePicker: 1,
    Timeline: 1,
    Tooltip: 1,
  },
  MaterialUI: {
    Alert: 1,
    AppBar: 1,
    Autocomplete: 1,
    Avatar: 1,
    Badge: 1,
    BottomNavigation: 1,
    Breadcrumbs: 1,
    Button: 1,
    ButtonGroup: 1,
    CSSBaseline: 1,
    Card: 1,
    Checkbox: 1,
    Chip: 1,
    ClickAwayListener: 1,
    Container: 1,
    DataGrid: 1,
    DatePickers: 1,
    Dialog: 1,
    Divider: 1,
    Drawer: 1,
    FAB: 1,
    Grid: 1,
    Grid2: 1,
    Hidden: 1,
    Icons: 1,
    ImageList: 1,
    Link: 1,
    List: 1,
    Masonry: 1,
    Menu: 1,
    Modal: 1,
    NoSSR: 1,
    Pagination: 1,
    Paper: 1,
    Popover: 1,
    Popper: 1,
    Portal: 1,
    Progress: 1,
    RadioGroup: 1,
    Rating: 1,
    Select: 1,
    Skeleton: 1,
    Slider: 1,
    Snackbar: 1,
    SpeedDial: 1,
    Stack: 1,
    Stepper: 1,
    Switch: 1,
    Table: 1,
    Tabs: 1,
    TextField: 1,
    TextareaAutosize: 1,
    Timeline: 1,
    ToggleButton: 1,
    Tooltip: 1,
    TransferList: 1,
    Typography: 1,
  },
  NextUI: {
    Accordion: 1,
    Autocomplete: 1,
    Avatar: 1,
    Badge: 1,
    Breadcrumbs: 1,
    Button: 1,
    Card: 1,
    Checkbox: 1,
    CheckboxGroup: 1,
    Chip: 1,
    CircularProgress: 1,
    Code: 1,
    Divider: 1,
    Dropdown: 1,
    Image: 1,
    Input: 1,
    Kbd: 1,
    Link: 1,
    Listbox: 1,
    Modal: 1,
    Navbar: 1,
    Pagination: 1,
    Popover: 1,
    Progress: 1,
    RadioGroup: 1,
    ScrollShadow: 1,
    Select: 1,
    Skeleton: 1,
    Slider: 1,
    Snippet: 1,
    Spacer: 1,
    Spinner: 1,
    Switch: 1,
    Table: 1,
    Tabs: 1,
    Textarea: 1,
    Tooltip: 1,
    User: 1,
  },
  RadixUI: {
    AlertDialog: 1,
    AspectRatio: 1,
    Avatar: 1,
    Badge: 1,
    Button: 1,
    Callout: 1,
    Card: 1,
    Checkbox: 1,
    CheckboxCards: 1,
    CheckboxGroup: 1,
    ContextMenu: 1,
    DataList: 1,
    Dialog: 1,
    DropdownMenu: 1,
    HoverCard: 1,
    IconButton: 1,
    Inset: 1,
    Popover: 1,
    Progress: 1,
    Radio: 1,
    RadioCards: 1,
    RadioGroup: 1,
    ScrollArea: 1,
    SegmentedControl: 1,
    Select: 1,
    Separator: 1,
    Skeleton: 1,
    Slider: 1,
    Spinner: 1,
    Switch: 1,
    TabNav: 1,
    Table: 1,
    Tabs: 1,
    TextArea: 1,
    TextField: 1,
    Tooltip: 1,
  },
  ShadcnUI: {
    Accordion: 1,
    Alert: 1,
    AlertDialog: 1,
    AspectRatio: 1,
    Avatar: 1,
    Badge: 1,
    Breadcrumb: 1,
    Button: 1,
    Calendar: 1,
    Card: 1,
    Carousel: 1,
    Checkbox: 1,
    Collapsible: 1,
    Combobox: 1,
    Command: 1,
    ContextMenu: 1,
    DataTable: 1,
    DatePicker: 1,
    Dialog: 1,
    Drawer: 1,
    DropdownMenu: 1,
    Form: 1,
    HoverCard: 1,
    Input: 1,
    InputOTP: 1,
    Label: 1,
    Menubar: 1,
    NavigationMenu: 1,
    Pagination: 1,
    Popover: 1,
    Progress: 1,
    RadioGroup: 1,
    Resizable: 1,
    ScrollArea: 1,
    Select: 1,
    Separator: 1,
    Sheet: 1,
    Skeleton: 1,
    Slider: 1,
    Sonner: 1,
    Switch: 1,
    Table: 1,
    Tabs: 1,
    Textarea: 1,
    Toast: 1,
    Toggle: 1,
    ToggleGroup: 1,
    Tooltip: 1,
  },
};
export const UiComponents = [
  "Accordion",
  "Alert",
  "AlertDialog",
  "AspectRatio",
  "Autocomplete",
  "Avatar",
  "Badge",
  "Breadcrumbs",
  "Button",
  "Callout",
  "Card",
  "Carousel",
  "Checkbox",
  "CheckboxCards",
  "CheckboxGroup",
  "Chip",
  "CircularProgress",
  "Code",
  "Collapse",
  "ContextMenu",
  "DataList",
  "Descriptions",
  "Dialog",
  "Divider",
  "Drawer",
  "Dropdown",
  "DropdownMenu",
  "Empty",
  "HoverCard",
  "IconButton",
  "Image",
  "Input",
  "InputNumber",
  "Inset",
  "Kbd",
  "Link",
  "List",
  "Listbox",
  "Mentions",
  "Message",
  "Modal",
  "Navbar",
  "Notification",
  "Pagination",
  "Popover",
  "Popconfirm",
  "Progress",
  "QRCode",
  "Radio",
  "RadioCards",
  "RadioGroup",
  "Rate",
  "Result",
  "ScrollArea",
  "ScrollShadow",
  "Segmented",
  "SegmentedControl",
  "Select",
  "Separator",
  "Skeleton",
  "Slider",
  "Snippet",
  "Spacer",
  "Spinner",
  "Spin",
  "Switch",
  "Table",
  "Tabs",
  "TabNav",
  "Tag",
  "Textarea",
  "TextField",
  "Timeline",
  "TimePicker",
  "Tooltip",
  "Tour",
  "Transfer",
  "Tree",
  "TreeSelect",
  "Upload",
  "User",
  "Watermark",
];

export const UiComponentsDescription: {
  [key in string]: string;
} = {
  Accordion:
    "A vertically stacked list of headers that reveal or hide more content when clicked.",
  AlertDialog: "A modal dialog that alerts the user of a situation.",
  AspectRatio: "A component that maintains a fixed aspect ratio.",
  Autocomplete: "A text input field that provides suggestions while you type.",
  Avatar: "A component for displaying user profile pictures.",
  Badge: "A small count and labeling component that adds context to content.",
  Breadcrumbs:
    "A navigation aid that shows the user's location in a site or application.",
  Button: "An interactive element that triggers an action when clicked.",
  Card: "A flexible container for displaying content and actions on a single topic.",
  Checkbox:
    "An input control that allows a user to select one or more options from a set.",
  CheckboxCards: "A group of cards that can be selected or deselected.",
  CheckboxGroup:
    "A group of checkboxes that can be used to allow multiple selections.",
  Chip: "A compact element that represents an input, attribute, or action.",
  CircularProgress:
    "A circular graphical representation of progress in a task.",
  Code: "A component for displaying blocks of code with syntax highlighting.",
  ContextMenu:
    "A context menu that appears when a user right-clicks on an element.",
  DataList: "A list of data items that can be filtered and searched.",
  Dialog: "A modal dialog that requires user interaction.",
  Divider: "A thin line that groups content in lists and layouts.",
  Dropdown:
    "A list of options that drops down from a control that users can select from.",
  DropdownMenu: "A menu that appears when a user clicks on a control.",
  HoverCard: "A card that appears when a user hovers over an element.",
  IconButton: "A button that displays an icon.",
  Image: "A component for displaying images.",
  Input: "A field used to get user input in a form.",
  Inset: "A component that creates a visual inset.",
  Kbd: "A component that displays keyboard inputs.",
  Link: "A navigational element that allows users to click through to another page or site.",
  Listbox:
    "A graphical control element that allows the user to select one or more items from a list.",
  Modal:
    "A dialog box/popup window that is displayed on top of the current page.",
  Navbar: "A navigation header that is placed at the top of the page.",
  Pagination:
    "A component that allows the user to select a specific page from a range.",
  Popover: "A small, contextual overlay that opens on demand.",
  Progress:
    "A component to display the progress status for a task that takes a long time or consists of several steps.",
  Radio: "A radio button that allows the user to select one option.",
  RadioGroup:
    "A group of radio buttons that allows the user to select one option from a set.",
  ScrollArea: "A scrollable area that contains content.",
  ScrollShadow:
    "A visual effect that indicates more content is available in a scrollable area.",
  SegmentedControl:
    "A control that allows the user to select one option from a set.",
  Select:
    "A control that allows the user to choose one option from a dropdown list.",
  Separator: "A visual element that separates content.",
  Skeleton:
    "A placeholder component used to improve content loading experience.",
  Slider: "A component that allows the user to select a value from a range.",
  Snippet: "A small piece of reusable code or text.",
  Spacer:
    "An invisible component used to create space between elements in layouts.",
  Spinner: "A component that shows a loading indicator.",
  Switch: "A component that allows the user to toggle between two states.",
  Table: "A component for displaying data in a tabular format.",
  Tabs: "A component that organizes content into separate views.",

  Textarea: "A multi-line text input field.",
  Tooltip:
    "A small pop-up box that appears when a user hovers over an element.",
  User: "A component that displays user information.",
};
